#!/bin/bash

export PD_PROJECT_DIR=`pwd`
export PD_BUILD_COMMIT_HASH=`cd $PD_PROJECT_DIR && git rev-parse --short HEAD`
export PD_BUILD_TAG=`cd $PD_PROJECT_DIR && git describe --tags --abbrev=0`
export PD_BUILD_DATETIME=`date +"%y-%m-%d-%H%M%S"`
export PD_BUILD_DIR=`pwd`/PRODUCTS/$PD_BUILD_DATETIME/PolarDesigner
export PD_BUILD_VERSION=`cat $PD_PROJECT_DIR/VERSION`
export PD_BUILD_ARCHIVE=`pwd`/ARCHIVE/
export PD_BUILD_SYSTYPE=`../../Tools/check_os.sh`
export PD_BUILD_TYPE="Release"
export PD_BUILD_MARK=${PD_BUILD_VERSION}_${PD_BUILD_SYSTYPE}_${PD_BUILD_TYPE}_${PD_BUILD_DATETIME}_${PD_BUILD_TAG}_${PD_BUILD_COMMIT_HASH}
export PD_BUILD_TARBALL=$PD_BUILD_ARCHIVE/PolarDesigner_${PD_BUILD_MARK}.tar.gz
export PD_BUILD_MACOS_DISKIMAGE=$PD_BUILD_ARCHIVE/PolarDesigner_${PD_BUILD_MARK}.dmg
export PD_BUILD_ARCHIVE_DESTINATION=devops@192.168.1.48:/Users/devops/Desktop/BUILD_ARCHIVE/

echo "Build Variables:"
echo "PD_PROJECT_DIR=$PD_PROJECT_DIR"
echo "PD_BUILD_COMMIT_HASH=$PD_BUILD_COMMIT_HASH"
echo "PD_BUILD_TAG=$PD_BUILD_TAG"
echo "PD_BUILD_MARK=$PD_BUILD_MARK"
echo "PD_BUILD_DATE_TIME=$PD_BUILD_DATETIME"
echo "PD_BUILD_TYPE=$PD_BUILD_TYPE"
echo "PD_BUILD_DIR=$PD_BUILD_DIR"
echo "PD_BUILD_VERSION=$PD_BUILD_VERSION"
echo "PD_BUILD_ARCHIVE=$PD_BUILD_ARCHIVE"
echo "PD_BUILD_SYSTYPE=$PD_BUILD_SYSTYPE"
echo "PD_BUILD_TARBALL=$PD_BUILD_TARBALL"
echo "PD_BUILD_MACOS_DISKIMAGE=$PD_BUILD_MACOS_DISKIMAGE"
echo "PD_BUILD_ARCHIVE_DESTINATION=$PD_BUILD_ARCHIVE_DESTINATION"

echo "------"
echo "Current MARK of PolarDesigner: $PD_BUILD_MARK" 
echo "------"
